"""Sync production missing columns

Revision ID: a70e4e126d2d
Revises: af211b1f1de8
Create Date: 2026-09-08 02:24:07.952339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a70e4e126d2d'
down_revision: Union[str, Sequence[str], None] = 'af211b1f1de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest_participants', sa.Column('tab_switches', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('contest_participants', sa.Column('locked', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('contests', sa.Column('max_tab_switches', sa.Integer(), nullable=False, server_default=sa.text('3')))
    op.add_column('contests', sa.Column('proctor_password', sa.String(length=200), nullable=True))
    op.drop_column('problems', 'debugging_data')
    op.drop_column('problems', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('type', sa.VARCHAR(length=20), server_default=sa.text("'coding'::character varying"), autoincrement=False, nullable=False))
    op.add_column('problems', sa.Column('debugging_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('contests', 'proctor_password')
    op.drop_column('contests', 'max_tab_switches')
    op.drop_column('contest_participants', 'locked')
    op.drop_column('contest_participants', 'tab_switches')
    # ### end Alembic commands ###
