import { useGuideLogic } from "../../hooks/useGuideLogic";
import Navbar from "../../components/Navbar";
import {
  CompareTable,
  FlowDiagram,
  InfoCards,
  Layers,
  MergeChart,
  OrgChart,
} from "../../components/guide/OopsDiagrams";

export default function OopsVisualGuidePage() {
  useGuideLogic();
  return (
    <div className="min-h-screen bg-background text-foreground">
      <Navbar />

      <div className="layout">
        <nav className="sidebar" aria-label="Topic navigation">
          <div className="sidebar-title">OOPs Visual Blueprint</div>
          <div className="side-group">
            <div className="side-group-label">Foundations</div>
            <a className="side-link" href="#q1">01 · Intro to OOPs</a>
            <a className="side-link" href="#q2">02 · Classes &amp; Objects</a>
          </div>
          <div className="side-group">
            <div className="side-group-label">The Four Pillars</div>
            <a className="side-link" href="#q3">03 · Encapsulation</a>
            <a className="side-link" href="#q4">04 · Abstraction</a>
            <a className="side-link" href="#q5">05 · Inheritance</a>
            <a className="side-link" href="#q6">06 · Polymorphism</a>
          </div>
        </nav>

        <div className="main">
          <div className="topbar">
            <div className="brand">
              <span className="mark">OOPs Visual</span>
              <span className="sub">Zero to Code · Blueprint diagrams</span>
            </div>
          </div>

          <div className="question-nav">
            <button type="button" id="prevQuestionBtn">← Previous</button>
            <span className="question-nav-progress" id="questionProgress" />
            <button type="button" id="nextQuestionBtn">Next →</button>
          </div>

          <div className="content">
            <div className="intro">
              <h1>Zero to Code: The OOPs Blueprint</h1>
              <p>
                Six diagram-first topics that map Object-Oriented Programming
                straight to real-world entities — the same way a whiteboard
                interview explanation should look.
              </p>
              <div className="legend">
                <span className="legend-item">Concept &amp; diagram</span>
                <span className="legend-item">Interview tip</span>
              </div>
            </div>

            <section className="question" id="q1">
              <div className="q-head">
                <span className="q-index">01</span>
                <h2>What is OOPs?</h2>
                <span className="level-badge reference">Foundation</span>
              </div>
              <p className="prompt">
                Object-Oriented Programming organizes software design around{" "}
                <b>data (objects)</b> rather than functions and logic — it
                maps software concepts directly to real-world entities,
                unlike the step-by-step instructions of procedural code.
              </p>

              <h3 style={{ marginTop: 16 }}>Procedural (Top-Down)</h3>
              <FlowDiagram nodes={["Fetch User Data", "Calculate Total", "Process Payment"]} />

              <h3 style={{ marginTop: 16 }}>OOPs (Interacting Entities)</h3>
              <InfoCards
                cards={[
                  { title: "User Object", desc: "Holds the customer's identity and session data.", color: "#3b82f6" },
                  { title: "Cart Object", desc: "Holds selected items and quantities, independent of the user.", color: "#a371f7" },
                  { title: "Invoice Object", desc: "Generated by combining User and Cart state into a billable record.", color: "#059669" },
                ]}
              />

              <div className="twist">
                <strong>Interview tip:</strong> when asked "Why use OOPs?",
                don't just say "it uses classes." Say: OOPs provides{" "}
                <b>Modularity</b> (easier troubleshooting), <b>Reusability</b>{" "}
                (through inheritance), and <b>Security</b> (through
                encapsulation).
              </div>
            </section>

            <section className="question" id="q2">
              <div className="q-head">
                <span className="q-index">02</span>
                <h2>Classes &amp; Objects</h2>
                <span className="level-badge basic">Basic</span>
              </div>
              <p className="prompt">
                A <b>Class</b> is a blueprint (logical entity). An{" "}
                <b>Object</b> is an instance of that class (physical entity)
                that occupies memory.
              </p>

              <OrgChart
                root="House Blueprint — has Color, has Doors, can Open()"
                children={[
                  { label: "House 1 · Color: Red" },
                  { label: "House 2 · Color: Blue" },
                  { label: "House 3 · Color: Green" },
                ]}
              />

              <div className="twist">
                <strong>Interview tip:</strong> a Class does <b>not</b>{" "}
                allocate memory when created — it's just a definition. Memory
                is only allocated when an Object is instantiated using the{" "}
                <code>new</code> keyword.
              </div>
            </section>

            <section className="question" id="q3">
              <div className="q-head">
                <span className="q-index">03</span>
                <h2>Encapsulation — The ATM Metaphor</h2>
                <span className="level-badge basic">Basic</span>
              </div>
              <p className="prompt">
                Encapsulation bundles data (variables) and methods into a
                single unit, hiding the internal state from the outside world
                (data hiding).
              </p>

              <Layers
                visible="Public methods: withdraw(), deposit() — validates every request before touching the vault"
                hidden="Private data (vault): Total_Balance — never accessed directly from outside the class"
              />

              <div className="twist">
                <strong>Interview tip:</strong> encapsulation isn't just about
                security — it's also about <b>control and flexibility</b>.
                You can make a variable read-only (getter but no setter) or
                change the internal data type later without breaking the code
                that relies on the public methods.
              </div>
            </section>

            <section className="question" id="q4">
              <div className="q-head">
                <span className="q-index">04</span>
                <h2>Abstraction — The Car Dashboard</h2>
                <span className="level-badge basic">Basic</span>
              </div>
              <p className="prompt">
                Abstraction shows only essential attributes and hides
                unnecessary internal details from the user, reducing
                complexity.
              </p>

              <CompareTable
                headers={["Visible to Driver (Essential)", "Hidden Complexity (Ignored)"]}
                rows={[
                  ["Steering wheel", "Combustion engine"],
                  ["Accelerator pedal", "Fuel injection system"],
                  ["Brake pedal", "Alternator mechanics"],
                ]}
              />

              <div className="twist">
                <strong>Interview tip:</strong> don't confuse Abstraction with
                Encapsulation. <b>Abstraction</b> hides complexity (design
                level: <i>what</i> it does), while <b>Encapsulation</b> hides
                data (implementation level: <i>how</i> it protects the
                internal state).
              </div>
            </section>

            <section className="question" id="q5">
              <div className="q-head">
                <span className="q-index">05</span>
                <h2>Inheritance — All 5 Types</h2>
                <span className="level-badge medium">Medium</span>
              </div>
              <p className="prompt">
                Inheritance lets a new class (child) acquire properties and
                methods of an existing class (parent), supporting
                hierarchical classification and code reusability. There are
                exactly <b>5 types</b>.
              </p>

              <h3 style={{ marginTop: 16 }}>1 · Single Inheritance</h3>
              <FlowDiagram nodes={["Animal (Parent)", "Dog (Child)"]} />

              <h3 style={{ marginTop: 16 }}>2 · Multiple Inheritance</h3>
              <MergeChart parents={["Camera", "Phone"]} child="Smartphone" />

              <h3 style={{ marginTop: 16 }}>3 · Multilevel Inheritance</h3>
              <FlowDiagram nodes={["Vehicle (Grandparent)", "Car (Parent)", "Electric Car (Child)"]} />

              <h3 style={{ marginTop: 16 }}>4 · Hierarchical Inheritance</h3>
              <OrgChart
                root="Employee (Parent)"
                children={[{ label: "Manager" }, { label: "Developer" }, { label: "Designer" }]}
              />

              <h3 style={{ marginTop: 16 }}>5 · Hybrid Inheritance (Diamond)</h3>
              <OrgChart root="Vehicle" children={[{ label: "WaterCraft" }, { label: "LandCraft" }]} />
              <MergeChart parents={["WaterCraft", "LandCraft"]} child="Amphibious" />
              <div className="example">Combines Hierarchical + Multiple Inheritance.</div>

              <div className="twist">
                <strong>Python vs Java:</strong> Python supports multiple
                inheritance using Method Resolution Order (MRO) / C3
                Linearization to solve the diamond problem natively. Java
                avoids it with classes directly and uses{" "}
                <b>Interfaces</b> instead to achieve the same result safely.
              </div>
            </section>

            <section className="question" id="q6">
              <div className="q-head">
                <span className="q-index">06</span>
                <h2>Polymorphism — Many Forms</h2>
                <span className="level-badge basic">Basic</span>
              </div>
              <p className="prompt">
                Polymorphism means "many forms." It allows methods to do
                different things based on the object it is acting upon or the
                parameters passed.
              </p>

              <h3 style={{ marginTop: 16 }}>Compile-time (Static Binding) — Overloading</h3>
              <InfoCards
                cards={[
                  { title: "calculateArea(radius)", desc: "Circle area — one parameter.", color: "#f59e0b" },
                  { title: "calculateArea(len, wid)", desc: "Rectangle area — two parameters.", color: "#3b82f6" },
                  { title: "calculateArea(b, h, type)", desc: "Triangle area — three parameters.", color: "#a371f7" },
                ]}
              />

              <h3 style={{ marginTop: 16 }}>Run-time (Dynamic Binding) — Overriding</h3>
              <OrgChart
                root="Animal.makeSound()"
                children={[{ label: "Dog Class → \"Bark!\"" }, { label: "Cat Class → \"Meow!\"" }]}
              />

              <CompareTable
                headers={["Compile-Time Polymorphism", "Runtime Polymorphism"]}
                rows={[
                  ["Static / early binding", "Dynamic / late binding"],
                  ["Achieved via method overloading", "Achieved via method overriding"],
                  ["Compiler decides the call", "JVM/interpreter decides, based on actual object"],
                ]}
              />

              <div className="twist">
                <strong>Interview tip:</strong> <b>Overloading = Compile-Time</b>{" "}
                (early binding, handled by compiler). <b>Overriding = Run-Time</b>{" "}
                (late binding, handled by JVM/interpreter based on the actual
                object type created).
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
